# Generated by Django 4.0 on 2022-09-04 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price_per_unit',
        ),
    ]
